### PR TITLE
👌 IMPROVE: linux distro fetching method, pep8

### PR DESCRIPTION
**Pull request by TechWiz-3**
In this PR I have:
* Addressed #6 with use of the [distro](https://github.com/python-distro/distro) library
* Improved readability with pep8 standards

Please feel free to do whatever you wish with this PR as it represents my specific opinions and preferences 👍

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Oh and here after the 'after' screenshots

Screen Shot 2022-06-30 at 12 55 32 am
Screen Shot 2022-06-30 at 12 55 26 am

**Comment by beucismis** [comment]
I don't want to use 3rd party libraries. Pure Python.

**Comment by TechWiz-3** [comment]
Fair enough, in any case you might want to look into another pure python method for getting the distro pretty name

**Comment by beucismis** [comment]
I will close this PR. If you wish, you can change the name of the project fork and improve it.

**Comment by TechWiz-3** [comment]
Ok I'm just curious, why do you want to only use pure python?

**Comment by beucismis** [comment]
I think it can be solved without using 3 party modules. Also thank you for your support...

**Pull request closed without merging**
