### PR TITLE
add gcc version, pip number of packages and fix processor name

### PR DESCRIPTION
**Pull request by TheCrether**
I changed the processor name part because it is unreliable (didn't work on my machine for example)

### CODE REVIEW

**Comment by beucismis** [comment]
Sorry I didn't see your PR... Can you make changes on `v0.2.1` ?

**Comment by TheCrether** [comment]
i made the changes

**Comment by beucismis** [comment]
Thanks for contribute.

**Comment by beucismis** [comment]
`pip3 list` output too slow... It takes 3-4 seconds.

Issue: #3

**Pull request merged**
